#!/bin/bash 
#setup script for dev environment

downloadfolder="$HOME/Downloads"  #location for downloaded installation files
whoisthis="Eric Harrison"  #your name, used for Git config
youremail="ericmharrison@gmail.com"  #your email, used for Git config

#update package list and upgrade all software
sudo apt-get update && sudo apt-get -fy upgrade